server:
  port: 9001
spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    username: root
    password: szPulan_!QAsw2
    url: jdbc:mysql://192.168.1.43:3306/yousayidoprop?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000
    filters: stat,wall,log4j
    logSlowSql: true

#DataSource for Redis
#jedis:
#  pool:
#    host: 120.79.243.95
#    port: 6379
#    password: AI-assist-MQ
#    maxTotal: 100
#    maxIdle: 5
#    maxWaitMillis: -1
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
jedis:
  pool:
    host: 192.168.1.43
    port: 6379
    password: AI-assist-MQ
    maxTotal: 100
    maxIdle: 5
    maxWaitMillis: -1
redis:
  tmKey: tm_chat_record
  recordUpdateForSIP: RecordUpdateQuene #用于通知sip更新录音文件的队列
  recordSynthesis: RecordSynthesisQuene #用于处理TTS合成失败
  algorithmDataSyn: AlgorithmDataSynQueue #用户同步算法数据

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.pl.model,com.pl.indexserver.model
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    #lazyLoadingEnabled: true
    #multipleResultSetsEnabled: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#jiguang
jiguang:
  mastersecret: 4b9b1c29efd1109cfde08b84
  appkey: 24286bbb7fde1ab272b71a6e
  templateId: 1

#录音文件地址
recordings:
  address: http://192.168.1.99:8800/recordManagement
  ftpPath: /tm
  ftpPath_local: /tm

custom:
  record-path:
  excel-path: xlxs

#系统管理员相关配置
pl:
  allAuth: all

#ftp相关配置
ftp:
  address: 192.168.1.43
  port: 8021
  name: apache
  password: szPulan

#tts相关配置
tts:
  url: http://tsn.baidu.com/text2audio
  api_key: ZcL3uxCrjKcZW73Z1POdamOO
  secret_key: RujZIvc4FObKiGuBxLL2da47uRVF3rfW
  vol: 5  #音量，取值0-15，默认为5中音量
  per: 0  #发音人选择, 0为普通女声，1为普通男生，3为情感合成-度逍遥，4为情感合成-度丫丫，默认为普通女声
  spd: 5  #语速，取值0-15，默认为5中语速
  pit: 5  #音调，取值0-15，默认为5中语调

# 智库方案的默认呼叫地址
t_business:
  default:
    controll_addr: http://192.168.1.43:9002/busiManagement/dialog/startCallTask

#微信第三方登录
weixin:
  AppId: wx983ce646b7d0d472
  AppSecret: acf7c33f228a86dead9d202ac0e78f46
  tokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token?
  bindUrl: http://ai.yousayido.net/ai_tm/temaple/bind.html
task:
  switch: false

#微信公众测试号
weixintest:
  AppId: wx93e9fc5be7062cc1
  AppSecret: 57f7cfd23cf48b75e757470c67eeaa50

#小兵秘书微信公众号
xiaobingsecretary:
  AppId: wxec01266416a98d18
  AppSecret: b7637c7420653061e4f9d069743c7f0f
 
# DubboDemoService service version
thirdparty:
  service:
    version: 1.0.0
autodialer:
  service:
    version: 1.0.0
  enableStats: false
# Dubbo Config properties
# Base packages to scan Dubbo Component: @com.alibaba.dubbo.config.annotation.Service
## ApplicationConfig Bean
## ProtocolConfig Bean
## RegistryConfig Bean
dubbo:
    application:
        id: index-server
        name: index-server
    protocol:
        id: dubbo
        name: dubbo
        port: 20880
    registry:
        address: zookeeper://192.168.1.43:2181
        id: plRegistry
        

        